services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cp-myanez-landing
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - coolify

networks:
  coolify:
    name: coolify
    driver: bridge
